# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [justins1025, mouse3687]
patreon: # Replace with a single Patreon https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username https://sans.org
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username kllm
issuehunt: # Replace with a single IssueHunt username bob barker
otechie: # Replace with a single Otechie username CDC.Gov
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['ASPCA', 'foxtrot']
